// Users
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// Avatars
export const FETCH_USERS_AVATARS_REQUEST = 'FETCH_USERS_AVATARS_REQUEST';
export const FETCH_USERS_AVATARS_SUCCESS = 'FETCH_USERS_AVATARS_SUCCESS';
export const FETCH_USERS_AVATARS_FAILURE = 'FETCH_USERS_AVATARS_FAILURE';

// Todos
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const CHANGE_TODO_STATUS_REQUEST = 'CHANGE_TODO_STATUS_REQUEST';
export const CHANGE_TODO_STATUS_SUCCESS = 'CHANGE_TODO_STATUS_SUCCESS';
export const CHANGE_TODO_STATUS_FAILURE = 'CHANGE_TODO_STATUS_FAILURE';

// Feeds
export const FETCH_FEEDS_REQUEST = 'FETCH_FEEDS_REQUEST';
export const FETCH_FEEDS_SUCCESS = 'FETCH_FEEDS_SUCCESS';
export const FETCH_FEEDS_FAILURE = 'FETCH_FEEDS_FAILURE';

export const DELETE_FEED_REQUEST = 'DELETE_FEED_REQUEST';
export const DELETE_FEED_SUCCESS = 'DELETE_FEED_SUCCESS';
export const DELETE_FEED_FAILURE = 'DELETE_FEED_FAILURE';

export const FETCH_FEED_COMMENTS_REQUEST = 'FETCH_FEED_COMMENTS_REQUEST';
export const FETCH_FEED_COMMENTS_SUCCESS = 'FETCH_FEED_COMMENTS_SUCCESS';
export const FETCH_FEED_COMMENTS_FAILURE = 'FETCH_FEED_COMMENTS_FAILURE';

export const POST_FEED_REQUEST = 'POST_FEED_REQUEST';
export const POST_FEED_SUCCESS = 'POST_FEED_SUCCESS';
export const POST_FEED_FAILURE = 'POST_FEED_FAILURE';